select ename, job, deptno
from emp
where job='CLERK';

SELECT ENAME, SAL, COMM 
FROM EMP
WHERE SAL<=COMM;

DESC EMP

SELECT DEPTNO, ENAME,SAL
FROM EMP
WHERE DEPTNO = 20;

SELECT EMPNO, ENAME, JOB, SAL
FROM EMP
WHERE EMPNO = 7788;

SELECT * FROM EMP
WHERE ENAME ='JAMES';

SELECT ENAME, JOB, SAL 
FROM EMP
WHERE JOB <> 'MANAGER';

SELECT * FROM EMP
WHERE SAL BETWEEN 1000 AND 2000;

SELECT ENAME, SAL, DEPTNO
FROM EMP
WHERE JOB IN ('PRESIDENT', 'ANALYST');

SELECT ENAME, SAL, DEPTNO
FROM EMP
WHERE JOB NOT IN('PRESIDENT', ' ANALYST');

select 
* from 
emp
where 
ename
like 'K%';

select * from jobs
where 
job_title like '%Clerk%';

select * from emp
where 
ename like '__L%';

Select ename ,mgr from emp
where mgr is null;

SELECT ENAME, JOB, SAL, SAL + 500
FROM EMP
WHERE JOB = 'ANALYST';

SELECT ENAME, JOB, SAL, 12*SAL + 200
FROM EMP;

SELECT ENAME, JOB, SAL,(12*SAL + 200)
FROM EMP;

DESC DEPT;

SELECT *FROM EMP;

SELECT ENAME, DEPTNO,SAL
FROM EMP;

SELECT DISTINCT JOB FROM EMP;

SELECT * FROM EMP
WHERE SAL > 2000;

SELECT ENAME, SAL, COMM
FROM EMP
WHERE SAL < COMM;

SELECT * FROM EMP
WHERE SAL BETWEEN 1000 AND 1500;

SELECT * FROM EMP
WHERE EMPNO IN (7902, 7788, 7876);

SELECT * FROM EMP
WHERE JOB NOT IN ('CLERK', 'MANAGER', 'ANALYST');

SELECT * FROM EMP
WHERE DEPTNO IN (10, 20);

SELECT SAL, (SAL * 14) + (1200 * 12)
FROM EMP WHERE ENAME = 'JONES';

SELECT ENAME, SAL, HIREDATE
FROM EMP ORDER BY SAL;

SELECT * FROM EMP
WHERE ENAME LIKE 'A%';

SELECT * FROM EMP
WHERE ENAME LIKE '_L%';

SELECT * FROM COUNTRIES 
WHERE COUNTRY_NAME LIKE 'N%';

SELECT * FROM EMPLOYEES
WHERE JOB_ID LIKE '%CLERK';




